const fs = require('fs');
const path = require('path');
const os = require('os');
const logger = require('../logger');

// Lazy-load to avoid circular dependency (registry discovers command files)
let _commands, _globalOptions;
function getRegistry() {
  if (!_commands) {
    const reg = require('../command-registry');
    _commands = reg.commands;
    _globalOptions = reg.globalOptions;
  }
  return { commands: _commands, globalOptions: _globalOptions };
}

function detectShell() {
  const shell = process.env.SHELL || '';
  if (shell.includes('zsh')) return 'zsh';
  if (shell.includes('fish')) return 'fish';
  return 'bash';
}

function escapeZsh(str) {
  return str.replace(/'/g, "'\\''");
}

function visibleCommands() {
  const { commands } = getRegistry();
  return commands.filter(c => !c.hidden && c.name !== '_default');
}

function generateZshCompletions() {
  const { globalOptions } = getRegistry();

  // Global option flags for _arguments
  const globalOptArgs = globalOptions
    .map(o => {
      const desc = escapeZsh(o.description);
      if (o.takesValue) {
        return `'${o.long}[${desc}]:'`;
      }
      return `'${o.long}[${desc}]'`;
    })
    .join(' \\\n    ');

  const cmdEntries = visibleCommands()
    .map(c => `      "${c.name}:${escapeZsh(c.description)}"`)
    .join('\n');

  // Build case branches for each command
  const caseBranches = visibleCommands()
    .map(c => {
      const parts = [];

      if (c.subcommands) {
        const subs = c.subcommands
          .filter(s => !s.hidden)
          .map(s => `"${s.name}:${escapeZsh(s.description)}"`)
          .join(' ');
        parts.push(`        local -a subcmds\n        subcmds=(${subs})\n        compadd -a subcmds`);
      }

      if (c.options && c.options.length > 0) {
        const optLines = c.options
          .map(o => {
            const desc = escapeZsh(o.description);
            if (o.completesFiles) {
              return `'${o.long}[${desc}]:file:_files'`;
            }
            if (o.takesValue) {
              return `'${o.long}[${desc}]:'`;
            }
            return `'${o.long}[${desc}]'`;
          })
          .join(' ');
        parts.push(`        _arguments ${optLines}`);
      }

      if (c.args && c.args.length > 0) {
        // Check for known value sets (like shell types)
        if (c.name === 'completions') {
          parts.push('        compadd zsh bash fish');
        }
      }

      if (parts.length === 0) return null;
      return `      ${c.name})\n${parts.join('\n')}\n        ;;`;
    })
    .filter(Boolean)
    .join('\n');

  return `#compdef drplr
# drplr CLI (https://github.com/jtsternberg/drplr) completions
# Generated by: drplr completions zsh
# Regenerate after updates: drplr completions zsh

function _drplr {
  local -a commands

  _arguments -C \\
    ${globalOptArgs} \\
    "1: :->cmnds" \\
    "*::arg:->args"

  case $state in
  cmnds)
    commands=(
${cmdEntries}
    )
    _describe "command" commands
    ;;
  args)
    case $words[1] in
${caseBranches}
    esac
    ;;
  esac
}

compdef _drplr drplr
`;
}

function generateBashCompletions() {
  const { globalOptions } = getRegistry();
  const cmdNames = visibleCommands().map(c => c.name).join(' ');

  const globalOpts = globalOptions
    .map(o => [o.long, o.short].filter(Boolean).join(' '))
    .join(' ');

  const caseBranches = visibleCommands()
    .map(c => {
      if (c.subcommands) {
        const subs = c.subcommands
          .filter(s => !s.hidden)
          .map(s => s.name)
          .join(' ');
        return `    ${c.name})\n      COMPREPLY=( $(compgen -W "${subs}" -- "\${cur}") )\n      return 0\n      ;;`;
      }
      if (c.options && c.options.length > 0) {
        // Deduplicate: command options + global options
        const allOpts = new Set([
          ...c.options.map(o => o.long),
          ...c.options.map(o => o.short).filter(Boolean),
          ...globalOptions.map(o => o.long),
          ...globalOptions.map(o => o.short).filter(Boolean)
        ]);
        return `    ${c.name})\n      COMPREPLY=( $(compgen -W "${[...allOpts].join(' ')}" -- "\${cur}") )\n      return 0\n      ;;`;
      }
      return null;
    })
    .filter(Boolean)
    .join('\n');

  return `# drplr CLI (https://github.com/jtsternberg/drplr) completions
# Generated by: drplr completions bash
# Regenerate after updates: drplr completions bash

_drplr_completions() {
  local cur prev
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"

  local commands="${cmdNames}"
  local global_opts="${globalOpts}"

  case "\${COMP_WORDS[1]}" in
${caseBranches}
    completions)
      COMPREPLY=( $(compgen -W "zsh bash fish" -- "\${cur}") )
      return 0
      ;;
    *)
      ;;
  esac

  if [[ \${COMP_CWORD} -eq 1 ]]; then
    # Complete commands and files for upload
    COMPREPLY=( $(compgen -W "\${commands}" -- "\${cur}") $(compgen -f -- "\${cur}") )
  else
    # Global options
    COMPREPLY=( $(compgen -W "\${global_opts}" -- "\${cur}") )
  fi

  return 0
}

complete -F _drplr_completions drplr
`;
}

function generateFishCompletions() {
  const { globalOptions } = getRegistry();
  const lines = [
    '# drplr CLI (https://github.com/jtsternberg/drplr) completions',
    '# Generated by: drplr completions fish',
    '# Regenerate after updates: drplr completions fish',
    ''
  ];

  // Commands
  lines.push('# Commands');
  for (const cmd of visibleCommands()) {
    lines.push(
      `complete -c drplr -n '__fish_use_subcommand' -a ${cmd.name} -d '${escapeZsh(cmd.description)}'`
    );
  }
  lines.push('');

  // Subcommand completions
  for (const cmd of visibleCommands().filter(c => c.subcommands)) {
    lines.push(`# ${cmd.name} subcommands`);
    for (const sub of cmd.subcommands.filter(s => !s.hidden)) {
      lines.push(
        `complete -c drplr -n '__fish_seen_subcommand_from ${cmd.name}' -a ${sub.name} -d '${escapeZsh(sub.description)}'`
      );
    }
    lines.push('');
  }

  // Option completions per command
  for (const cmd of visibleCommands().filter(c => c.options && c.options.length > 0)) {
    lines.push(`# ${cmd.name} options`);
    for (const opt of cmd.options) {
      const long = opt.long.replace(/^--/, '');
      const requiresArg = opt.takesValue ? ' -r' : '';
      const fileComplete = opt.completesFiles ? ' -F' : '';
      lines.push(
        `complete -c drplr -n '__fish_seen_subcommand_from ${cmd.name}' -l ${long}${requiresArg}${fileComplete} -d '${escapeZsh(opt.description)}'`
      );
    }
    lines.push('');
  }

  // Completions command
  lines.push('# completions shells');
  lines.push("complete -c drplr -n '__fish_seen_subcommand_from completions' -a 'zsh bash fish' -d 'Shell type'");
  lines.push('');

  // Global options
  lines.push('# Global options');
  for (const opt of globalOptions) {
    const long = opt.long.replace(/^--/, '');
    const requiresArg = opt.takesValue ? ' -r' : '';
    lines.push(
      `complete -c drplr -l ${long}${requiresArg} -d '${escapeZsh(opt.description)}'`
    );
  }
  lines.push('');

  return lines.join('\n');
}

function getRcFile(shell) {
  const home = os.homedir();
  switch (shell) {
    case 'zsh': return path.join(home, '.zshrc');
    case 'bash': return path.join(home, '.bashrc');
    case 'fish': return path.join(home, '.config', 'fish', 'config.fish');
    default: return '';
  }
}

function getEvalLine(shell) {
  switch (shell) {
    case 'zsh': return 'eval "$(drplr completions zsh)"';
    case 'bash': return 'eval "$(drplr completions bash)"';
    case 'fish': return 'drplr completions fish | source';
    default: return '';
  }
}

function installCompletions(shell) {
  const rcFile = getRcFile(shell);
  if (!rcFile) {
    logger.error(`Unsupported shell: ${shell}`);
    process.exit(1);
  }

  const evalLine = getEvalLine(shell);
  const comment = '# drplr CLI (https://github.com/jtsternberg/drplr) completions';

  // Check if already installed
  if (fs.existsSync(rcFile)) {
    const content = fs.readFileSync(rcFile, 'utf-8');
    if (content.includes('drplr completions')) {
      logger.log(`Completions already installed in ${rcFile}`);
      return;
    }
  }

  if (!fs.existsSync(rcFile)) {
    const dir = path.dirname(rcFile);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
    fs.writeFileSync(rcFile, `${comment}\n${evalLine}\n`);
  } else if (shell === 'zsh') {
    // For zsh, insert before compinit so completions are registered
    const content = fs.readFileSync(rcFile, 'utf-8');
    const lines = content.split('\n');

    // Find the last compinit line — insert after it so compdef works
    let compInitIdx = -1;
    for (let i = 0; i < lines.length; i++) {
      const trimmed = lines[i].trim();
      if (!trimmed.startsWith('#') && trimmed.includes('compinit')) {
        compInitIdx = i;
      }
    }

    if (compInitIdx >= 0) {
      lines.splice(compInitIdx + 1, 0, '', comment, evalLine);
    } else {
      // No compinit found, append
      lines.push('', comment, evalLine);
    }

    fs.writeFileSync(rcFile, lines.join('\n'), 'utf-8');
  } else {
    // bash/fish — just append
    fs.appendFileSync(rcFile, `\n${comment}\n${evalLine}\n`);
  }

  logger.log(`Added completions to ${rcFile}`);
  logger.log('');
  logger.log('Restart your shell or run:');
  logger.log(`  source ${rcFile}`);
}

function handleCompletionsCommand(args) {
  const install = args.includes('--install');
  const filteredArgs = args.filter(a => a !== '--install');
  const shell = filteredArgs[0] || detectShell();

  if (!['zsh', 'bash', 'fish'].includes(shell)) {
    logger.error(`Unsupported shell: ${shell}`);
    logger.error('Supported shells: zsh, bash, fish');
    logger.error('');
    logger.error('Usage: drplr completions [shell] [--install]');
    logger.error('');
    logger.error('Output completions:');
    logger.error('  eval "$(drplr completions zsh)"');
    logger.error('  eval "$(drplr completions bash)"');
    logger.error('  drplr completions fish | source');
    logger.error('');
    logger.error('Install completions:');
    logger.error('  drplr completions --install');
    process.exit(1);
  }

  if (install) {
    installCompletions(shell);
  } else {
    process.stdout.write(
      shell === 'zsh' ? generateZshCompletions() :
      shell === 'bash' ? generateBashCompletions() :
      generateFishCompletions()
    );
  }
}

const meta = {
  name: 'completions',
  description: 'Generate shell completions',
  args: [{ name: 'shell', description: 'Shell type (zsh, bash, fish)' }],
  options: [
    { long: '--install', description: 'Install completions to shell config' }
  ]
};

module.exports = { handleCompletionsCommand, meta };
