const logger = require('../logger');

// Lazy-load to avoid circular dependency (registry discovers command files)
let _commands, _globalOptions;
function getRegistry() {
  if (!_commands) {
    const reg = require('../command-registry');
    _commands = reg.commands;
    _globalOptions = reg.globalOptions;
  }
  return { commands: _commands, globalOptions: _globalOptions };
}

function detectShell() {
  const shell = process.env.SHELL || '';
  if (shell.includes('zsh')) return 'zsh';
  if (shell.includes('fish')) return 'fish';
  return 'bash';
}

function escapeZsh(str) {
  return str.replace(/'/g, "'\\''");
}

function visibleCommands() {
  const { commands } = getRegistry();
  return commands.filter(c => !c.hidden && c.name !== '_default');
}

function generateZshCompletions() {
  const { globalOptions } = getRegistry();
  const cmdList = visibleCommands()
    .map(c => `    '${c.name}:${escapeZsh(c.description)}'`)
    .join('\n');

  // Build case branches for each command
  const caseBranches = visibleCommands()
    .map(c => {
      if (c.subcommands) {
        const subs = c.subcommands
          .filter(s => !s.hidden)
          .map(s => `'${s.name}:${escapeZsh(s.description)}'`)
          .join(' ');
        return `        ${c.name})\n          local -a subcmds\n          subcmds=(${subs})\n          _describe 'subcommand' subcmds\n          ;;`;
      }
      if (c.options && c.options.length > 0) {
        const optLines = c.options
          .map(o => {
            const desc = escapeZsh(o.description);
            if (o.completesFiles) {
              return `            '${o.long}[${desc}]:file:_files'`;
            }
            if (o.takesValue) {
              return `            '${o.long}[${desc}]:value:'`;
            }
            return `            '${o.long}[${desc}]'`;
          })
          .join(' \\\n');
        return `        ${c.name})\n          _arguments \\\n${optLines}\n          ;;`;
      }
      return null;
    })
    .filter(Boolean)
    .join('\n');

  // Global options for file upload (default command)
  const globalOptLines = globalOptions
    .map(o => {
      const desc = escapeZsh(o.description);
      if (o.takesValue) {
        return `      '${o.long}[${desc}]:value:'`;
      }
      return `      '${o.long}[${desc}]'`;
    })
    .join(' \\\n');

  return `#compdef drplr
# drplr CLI (https://github.com/jtsternberg/drplr) completions
# Generated by: drplr completions zsh
# Regenerate after updates: drplr completions zsh

_drplr() {
  local -a commands
  commands=(
${cmdList}
  )

  _arguments -C \\
    '1:command:->command' \\
    '*::arg:->args'

  case $state in
    command)
      # Complete commands and fall back to file completion for uploads
      _alternative \\
        'commands:command:_describe "command" commands' \\
        'files:file:_files'
      ;;
    args)
      case $words[1] in
${caseBranches}
        completions)
          local -a shells
          shells=('zsh:Z shell' 'bash:Bourne Again Shell' 'fish:Friendly Interactive Shell')
          _describe 'shell' shells
          ;;
      esac
      ;;
  esac

  # Global options available everywhere
  _arguments \\
${globalOptLines}
}

_drplr "$@"
`;
}

function generateBashCompletions() {
  const { globalOptions } = getRegistry();
  const cmdNames = visibleCommands().map(c => c.name).join(' ');

  const globalOpts = globalOptions
    .map(o => [o.long, o.short].filter(Boolean).join(' '))
    .join(' ');

  const caseBranches = visibleCommands()
    .map(c => {
      if (c.subcommands) {
        const subs = c.subcommands
          .filter(s => !s.hidden)
          .map(s => s.name)
          .join(' ');
        return `    ${c.name})\n      COMPREPLY=( $(compgen -W "${subs}" -- "\${cur}") )\n      return 0\n      ;;`;
      }
      if (c.options && c.options.length > 0) {
        // Deduplicate: command options + global options
        const allOpts = new Set([
          ...c.options.map(o => o.long),
          ...c.options.map(o => o.short).filter(Boolean),
          ...globalOptions.map(o => o.long),
          ...globalOptions.map(o => o.short).filter(Boolean)
        ]);
        return `    ${c.name})\n      COMPREPLY=( $(compgen -W "${[...allOpts].join(' ')}" -- "\${cur}") )\n      return 0\n      ;;`;
      }
      return null;
    })
    .filter(Boolean)
    .join('\n');

  return `# drplr CLI (https://github.com/jtsternberg/drplr) completions
# Generated by: drplr completions bash
# Regenerate after updates: drplr completions bash

_drplr_completions() {
  local cur prev
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"

  local commands="${cmdNames}"
  local global_opts="${globalOpts}"

  case "\${COMP_WORDS[1]}" in
${caseBranches}
    completions)
      COMPREPLY=( $(compgen -W "zsh bash fish" -- "\${cur}") )
      return 0
      ;;
    *)
      ;;
  esac

  if [[ \${COMP_CWORD} -eq 1 ]]; then
    # Complete commands and files for upload
    COMPREPLY=( $(compgen -W "\${commands}" -- "\${cur}") $(compgen -f -- "\${cur}") )
  else
    # Global options
    COMPREPLY=( $(compgen -W "\${global_opts}" -- "\${cur}") )
  fi

  return 0
}

complete -F _drplr_completions drplr
`;
}

function generateFishCompletions() {
  const { globalOptions } = getRegistry();
  const lines = [
    '# drplr CLI (https://github.com/jtsternberg/drplr) completions',
    '# Generated by: drplr completions fish',
    '# Regenerate after updates: drplr completions fish',
    ''
  ];

  // Commands
  lines.push('# Commands');
  for (const cmd of visibleCommands()) {
    lines.push(
      `complete -c drplr -n '__fish_use_subcommand' -a ${cmd.name} -d '${escapeZsh(cmd.description)}'`
    );
  }
  lines.push('');

  // Subcommand completions
  for (const cmd of visibleCommands().filter(c => c.subcommands)) {
    lines.push(`# ${cmd.name} subcommands`);
    for (const sub of cmd.subcommands.filter(s => !s.hidden)) {
      lines.push(
        `complete -c drplr -n '__fish_seen_subcommand_from ${cmd.name}' -a ${sub.name} -d '${escapeZsh(sub.description)}'`
      );
    }
    lines.push('');
  }

  // Option completions per command
  for (const cmd of visibleCommands().filter(c => c.options && c.options.length > 0)) {
    lines.push(`# ${cmd.name} options`);
    for (const opt of cmd.options) {
      const long = opt.long.replace(/^--/, '');
      const requiresArg = opt.takesValue ? ' -r' : '';
      const fileComplete = opt.completesFiles ? ' -F' : '';
      lines.push(
        `complete -c drplr -n '__fish_seen_subcommand_from ${cmd.name}' -l ${long}${requiresArg}${fileComplete} -d '${escapeZsh(opt.description)}'`
      );
    }
    lines.push('');
  }

  // Completions command
  lines.push('# completions shells');
  lines.push("complete -c drplr -n '__fish_seen_subcommand_from completions' -a 'zsh bash fish' -d 'Shell type'");
  lines.push('');

  // Global options
  lines.push('# Global options');
  for (const opt of globalOptions) {
    const long = opt.long.replace(/^--/, '');
    const requiresArg = opt.takesValue ? ' -r' : '';
    lines.push(
      `complete -c drplr -l ${long}${requiresArg} -d '${escapeZsh(opt.description)}'`
    );
  }
  lines.push('');

  return lines.join('\n');
}

function handleCompletionsCommand(args) {
  const shell = args[0] || detectShell();

  switch (shell) {
    case 'zsh':
      process.stdout.write(generateZshCompletions());
      break;
    case 'bash':
      process.stdout.write(generateBashCompletions());
      break;
    case 'fish':
      process.stdout.write(generateFishCompletions());
      break;
    default:
      logger.error(`Unsupported shell: ${shell}`);
      logger.error('Supported shells: zsh, bash, fish');
      logger.error('');
      logger.error('Usage: drplr completions [shell]');
      logger.error('');
      logger.error('Load completions:');
      logger.error('  zsh:  eval "$(drplr completions zsh)"');
      logger.error('  bash: eval "$(drplr completions bash)"');
      logger.error('  fish: drplr completions fish | source');
      process.exit(1);
  }
}

const meta = {
  name: 'completions',
  description: 'Generate shell completions',
  args: [{ name: 'shell', description: 'Shell type (zsh, bash, fish)' }]
};

module.exports = { handleCompletionsCommand, meta };
